AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Example CRUD app for *dev (star-dev) meetup

  '
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs8.10
    Environment:
      Variables:
        USER_TABLE_NAME: app-test-star-dev-users
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: '''*'''
  StarDevGetUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://app-star-dev/9d2f602b6b056a0ec5493ec25aaddaea
      Handler: app.getUsers
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
      Events:
        StarDevGetUsers:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: /users
            Method: get
  StarDevGetUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://app-star-dev/6061357947c307ac3b709b6ce6719b75
      Handler: app.getUser
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
      Events:
        StarDevGetUser:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: /users/{id}
            Method: get
  StarDevCreateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://app-star-dev/7807677e4ff493a84debf2c551a56e3d
      Handler: app.createUser
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
      Events:
        StarDevCreateUser:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: /users
            Method: post
  StarDevDeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://app-star-dev/b13e3fb808efc4ffa296d62dab747832
      Handler: app.deleteUser
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
      Events:
        StarDevDeleteUser:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: /users/{id}
            Method: delete
  StarDevUpdateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://app-star-dev/6dc334ca540aa0cf87166184e4ccc1e7
      Handler: app.updateUser
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
      Events:
        StarDevUpdateUser:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: /users/{id}
            Method: put
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: app-test-star-dev-users
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
