AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example CRUD app for *dev (star-dev) meetup
  
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs8.10
    Environment:
      Variables:
        USER_TABLE_NAME: "app-test-star-dev-users"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"

  StarDevGetUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getUsers/
      Handler: app.getUsers
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Events:
        StarDevGetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /users
            Method: get
  StarDevCreateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createUser/
      Handler: app.createUser
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Events:
        StarDevCreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /users
            Method: post
  StarDevDeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: deleteUser/
      Handler: app.deleteUser
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Events:
        StarDevDeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /users/{id}
            Method: delete
  StarDevUpdateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: updateUser/
      Handler: app.updateUser
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Events:
        StarDevUpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /users/{id}
            Method: put

  # cloudformation db 
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: app-test-star-dev-users
      KeySchema: 
        -
          AttributeName: id
          KeyType: HASH
        # TODO: add created_at
        # -
        #   AttributeName: createdAt
        #   KeyType: RANGE
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
        # TODO: add created_at
        # -
        #   AttributeName: "createdAt"
        #   AttributeType: "N"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
